#include "elit21/shopify/ShopifyAppConfigGenerator.h"

#include "elit21/shopify/ShopifyApiVersion.h"
#include "elit21/shopify/ShopifyEndpoints.h"
#include "elit21/util/StringUtil.h"

#include <filesystem>
#include <fstream>
#include <sstream>

namespace elit21::shopify {
namespace {
std::string quote(const std::string& value) {
    std::string output{"\""};
    for (const char character : value) {
        if (character == '\\' || character == '\"') output.push_back('\\');
        if (character == '\n' || character == '\r') continue;
        output.push_back(character);
    }
    output.push_back('\"');
    return output;
}

std::string array(const std::vector<std::string>& values) {
    std::ostringstream output;
    output << '[';
    for (std::size_t index = 0; index < values.size(); ++index) {
        if (index) output << ", ";
        output << quote(values[index]);
    }
    output << ']';
    return output.str();
}
} // namespace

Result<void> ShopifyAppConfigurationSpec::validate() const {
    if (client_id.empty()) return Result<void>::failure("Shopify app client_id is empty");
    if (!ShopifyEndpoints::isHttpsUrl(application_url)) {
        return Result<void>::failure("Shopify application_url must use HTTPS");
    }
    if (redirect_urls.empty()) return Result<void>::failure("At least one Shopify redirect URL is required");
    for (const auto& redirect : redirect_urls) {
        if (!ShopifyEndpoints::isHttpsUrl(redirect)) {
            return Result<void>::failure("Every Shopify redirect URL must use HTTPS");
        }
    }
    if (webhook_uri.empty() || (webhook_uri.front() != '/' && !ShopifyEndpoints::isHttpsUrl(webhook_uri))) {
        return Result<void>::failure("Webhook URI must be an HTTPS URL or an application-relative path");
    }
    ShopifyApiVersion version(api_version);
    if (!version.valid()) return Result<void>::failure("Shopify API version is invalid");
    if (scopes.empty()) return Result<void>::failure("Shopify scopes are empty");
    return Result<void>::success();
}

std::vector<std::string> ShopifyAppConfigGenerator::operationalTopics() {
    return {"orders/paid", "orders/cancelled", "refunds/create", "products/update",
            "products/delete", "inventory_levels/update", "fulfillments/create",
            "fulfillments/update", "app/uninstalled"};
}

std::vector<std::string> ShopifyAppConfigGenerator::complianceTopics() {
    return {"customers/data_request", "customers/redact", "shop/redact"};
}

Result<std::string> ShopifyAppConfigGenerator::generateToml(const ShopifyAppConfigurationSpec& spec) {
    if (auto validation = spec.validate(); !validation) {
        return Result<std::string>::failure(validation.error());
    }
    std::ostringstream output;
    output << "# Generated by ELIT21 Shopify App Config Generator\n";
    output << "client_id = " << quote(spec.client_id) << "\n";
    output << "name = \"ELIT21 Shopify AliExpress Autonomous Manager\"\n";
    output << "application_url = " << quote(spec.application_url) << "\n";
    output << "embedded = " << (spec.embedded ? "true" : "false") << "\n\n";
    output << "[access_scopes]\n";
    output << "scopes = " << quote(spec.scopes.commaSeparated()) << "\n\n";
    output << "[auth]\n";
    output << "redirect_urls = " << array(spec.redirect_urls) << "\n\n";
    output << "[webhooks]\n";
    output << "api_version = " << quote(spec.api_version) << "\n\n";
    if (spec.include_operational_webhooks) {
        output << "[[webhooks.subscriptions]]\n";
        output << "topics = " << array(operationalTopics()) << "\n";
        output << "uri = " << quote(spec.webhook_uri) << "\n\n";
    }
    output << "[[webhooks.subscriptions]]\n";
    output << "compliance_topics = " << array(complianceTopics()) << "\n";
    output << "uri = " << quote(spec.webhook_uri) << "\n";
    return Result<std::string>::success(output.str());
}

Result<void> ShopifyAppConfigGenerator::writeAtomically(const ShopifyAppConfigurationSpec& spec,
                                                        const std::string& output_path) {
    auto generated = generateToml(spec);
    if (!generated) return Result<void>::failure(generated.error());
    const std::filesystem::path destination(output_path);
    std::error_code error;
    if (!destination.parent_path().empty()) std::filesystem::create_directories(destination.parent_path(), error);
    if (error) return Result<void>::failure("Unable to create Shopify app config directory: " + error.message());
    const auto temporary = destination.string() + ".tmp";
    {
        std::ofstream stream(temporary, std::ios::binary | std::ios::trunc);
        if (!stream) return Result<void>::failure("Unable to open temporary Shopify app config");
        stream << generated.value();
        stream.flush();
        if (!stream) return Result<void>::failure("Unable to write Shopify app config");
    }
    std::filesystem::rename(temporary, destination, error);
    if (error) {
        std::filesystem::remove(destination, error);
        error.clear();
        std::filesystem::rename(temporary, destination, error);
    }
    if (error) return Result<void>::failure("Unable to publish Shopify app config: " + error.message());
    return Result<void>::success();
}

} // namespace elit21::shopify
