set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

find_program(ELIT21_MINGW_C_COMPILER x86_64-w64-mingw32-gcc gcc REQUIRED)
find_program(ELIT21_MINGW_CXX_COMPILER x86_64-w64-mingw32-g++ g++ REQUIRED)
find_program(ELIT21_MINGW_RC_COMPILER x86_64-w64-mingw32-windres windres)

set(CMAKE_C_COMPILER "${ELIT21_MINGW_C_COMPILER}" CACHE FILEPATH "MinGW-w64 C compiler")
set(CMAKE_CXX_COMPILER "${ELIT21_MINGW_CXX_COMPILER}" CACHE FILEPATH "MinGW-w64 C++ compiler")
if(ELIT21_MINGW_RC_COMPILER)
    set(CMAKE_RC_COMPILER "${ELIT21_MINGW_RC_COMPILER}" CACHE FILEPATH "MinGW-w64 resource compiler")
endif()

if(DEFINED ENV{MINGW_PREFIX})
    file(TO_CMAKE_PATH "$ENV{MINGW_PREFIX}" ELIT21_MINGW_PREFIX)
elseif(EXISTS "/mingw64")
    set(ELIT21_MINGW_PREFIX "/mingw64")
endif()

if(ELIT21_MINGW_PREFIX)
    list(PREPEND CMAKE_PREFIX_PATH "${ELIT21_MINGW_PREFIX}")
    list(PREPEND CMAKE_FIND_ROOT_PATH "${ELIT21_MINGW_PREFIX}")
    set(ENV{PKG_CONFIG_PATH} "${ELIT21_MINGW_PREFIX}/lib/pkgconfig:${ELIT21_MINGW_PREFIX}/share/pkgconfig:$ENV{PKG_CONFIG_PATH}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
