option(ELIT21_ENABLE_CLANG_TIDY "Enable clang-tidy when available" OFF)
if(ELIT21_ENABLE_CLANG_TIDY)
 find_program(CLANG_TIDY_EXE NAMES clang-tidy)
 if(CLANG_TIDY_EXE)
  set(CMAKE_CXX_CLANG_TIDY "${CLANG_TIDY_EXE}")
 endif()
endif()
